# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6310746e05ea6f033ea22bbb826c4834c7e2ba1441f8413a4c77cab2004d9793eaa992ffd4f0bca8bc9bfd8edffa42aff9424e859eda1e2a79f7f052f2c32e73

test:
  secret_key_base: 522919d64e8bbe4574ae7d9d2b30fd84fa65756575220217efc43e085f7f8099b7fe777625af5eec4c4165b14791e635bdbe04efc05c5374038647a7247ece44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
